WebApp/Controllers/EquiposController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class EquiposController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;
        public EquiposController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        public IActionResult Index(int marca, int linea, int cat, string palabraClave)
        {
            List<Equipo> Equipos = new List<Equipo>();
            Equipos = _context.tblEquipos
                .Include(e => e.Marca)
                .Include(e => e.Linea)
                .Include(e => e.Categoria)
                .ToList();

            if (marca == 0 && linea == 0 && cat == 0 && palabraClave != null)
            {
                //Filtrar por palabra clave
                Equipos = _context.tblEquipos
                    .Where(x => x.Descripcion.Contains(palabraClave) || x.DescripcionLarga.Contains(palabraClave))
                .Include(e => e.Marca)
                .Include(e => e.Linea)
                .Include(e => e.Categoria)
                .ToList();
            }

            ViewData["Marcas"] = new SelectList(_context.tblMarcas.ToList(), "Id", "Name");
            ViewData["Lineas"] = new SelectList(_context.tblLineas.ToList(), "Id", "Name");
            ViewData["Categorias"] = new SelectList(_context.tblCategorias.ToList(), "Id", "Name");

            EquipoIndexViewModel Eivm = new EquipoIndexViewModel();
            Eivm.Equipos = Equipos;

            return View(Eivm);
        }

        public IActionResult CrearEquipo()
        {
            ViewData["Marcas"] = new SelectList(_context.tblMarcas.ToList(), "Id", "Name");
            ViewData["Lineas"] = new SelectList(_context.tblLineas.ToList(), "Id", "Name");
            ViewData["Categorias"] = new SelectList(_context.tblCategorias.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CrearEquipo(Equipo E)
        {
            if (ModelState.IsValid)
            {
                if (E.ImagenFile == null) E.ImagenUrl = "no-disponible.png";
                else
                {
                    string wwwRootPath = _environment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(E.ImagenFile.FileName);
                    string extension = Path.GetExtension(E.ImagenFile.FileName);
                    E.ImagenUrl = fileName + DateTime.Now.ToString("ddMMyyyyHHmmss") + extension; //foto08062022131545.png 

                    string path = Path.Combine(wwwRootPath + "/img/" + E.ImagenUrl);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await E.ImagenFile.CopyToAsync(fileStream);
                    }
                }
                _context.Add(E);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(E);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var E = _context.tblEquipos.Find(Id);
            if (E == null) return NotFound();
            _context.Remove(E);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Edit(int Id)
        {
            var E = await _context.tblEquipos.FindAsync(Id);
            if(E == null) return NotFound();
            return View(E);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Equipo E)
        {
            if (ModelState.IsValid)
            {
                if (E.ImagenFile == null) E.ImagenUrl = "no-disponible.png";
                else
                {
                    string wwwRootPath = _environment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(E.ImagenFile.FileName);
                    string extension = Path.GetExtension(E.ImagenFile.FileName);
                    E.ImagenUrl = fileName + DateTime.Now.ToString("ddMMyyyyHHmmss") + extension; //foto08062022131545.png 

                    string path = Path.Combine(wwwRootPath + "/img/" + E.ImagenUrl);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await E.ImagenFile.CopyToAsync(fileStream);
                    }
                }
                _context.Update(E);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(E);
        }




    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }
    }
}

WebApp/Controllers/LineasController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class LineasController : Controller
    {
        private readonly AppDbContext _context;

        public LineasController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index() // Views - Marcas - Index
        {
            var Lineas = _context.tblLineas.ToList();

            CreateLineaViewModel Clvm = new CreateLineaViewModel();
            Clvm.Lineas = Lineas;
            return View(Clvm);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create([Bind(Prefix = "Linea")] Linea L)
        {
            if (L == null) return View();

            if (ModelState.IsValid)
            {
                _context.Add(L);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(L);
        }

        [HttpGet]
        public IActionResult Edit(int IdLinea)
        {
            var Linea = _context.tblLineas.FirstOrDefault(m => m.Id == IdLinea);
            if (Linea == null) return NotFound();
            else
            {
                return View(Linea);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Linea Linea)
        {
            if (ModelState.IsValid)
            {
                _context.Update(Linea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Linea);
        }


        [HttpGet]
        public IActionResult Delete(int IdLinea)
        {
            var Linea = _context.tblLineas.FirstOrDefault(m => m.Id == IdLinea);
            if (Linea == null) return NotFound();
            else
            {
                return View(Linea);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Linea Linea)
        {
            _context.Remove(Linea);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



    }
}

WebApp/Controllers/MarcasController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class MarcasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Views/Home/Contact.cshtml
@{
    var Nombre = "Programacion Avanzada";
}
<h1>Contacto</h1>
<h3>Welcome <strong>@Nombre</strong></h3>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <div class="row mt-2">

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-copyright" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Marcas</h5>
                    <p class="card-text">Crea, Edita o Elimina Marcas en el Sistema para la administracion y gestion de Equipos Tecnologicos!</p>
                    <a asp-controller="Marcas" asp-action="Index"
                       class="btn btn-outline-danger col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-list" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Categorias</h5>
                    <p class="card-text">Crea, Edita o Elimina Categorias en el Sistema para la administracion y gestion de Equipos Tecnologicos!</p>
                    <a asp-controller="Categorias" asp-action="Index"
                       class="btn btn-outline-success col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-users-line" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Lineas</h5>
                    <p class="card-text">Crea, Edita o Elimina Lineas en el Sistema para la administracion y gestion de Equipos Tecnologicos!</p>
                    <a asp-controller="Lineas" asp-action="Index"
                       class="btn btn-outline-primary col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>


    </div>
    <div class="row mt-2">

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-laptop" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Equipos</h5>
                    <p class="card-text">Gestion de Equipos Tecnologicos!</p>
                    <a asp-controller="Equipos" asp-action="Index"
                       class="btn btn-outline-info col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-user-gear" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Usuarios</h5>
                    <p class="card-text">Crea, edita o elimina nuevos Usuarios del Sistema</p>
                    <a asp-controller="Usuarios" asp-action="Index"
                       class="btn btn-outline-warning col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-right-from-bracket" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Salir</h5>
                    <p class="card-text">Cerrar la Session Activa</p>
                    <a asp-controller="Usuarios" asp-action="Index"
                       class="btn btn-outline-secondary col-12">Log Out</a>
                </div>
            </div>
        </div>

    </div>
</div>